config/routes.rb
Rails.application.routes.draw do
  root "dinosaurs#index"

  resources :dinosaurs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dinosaur.rb
class Dinosaur < ApplicationRecord
  def self.order_by_name
    order(:name)
  end
end

class Dinosaur < ApplicationRecord
  def is_baby?
    age < 3
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dinosaurs_controller.rb
# app/controllers/dinosaurs_controller.rb

class DinosaursController < ApplicationController
  # ...

  def show
    @dinosaur = Dinosaur.find(params[:id])
  end

  def new
    @dinosaur = Dinosaur.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dinosaurs_helper.rb
module DinosaursHelper
end

app/views/dinosaurs/index.html.erb
<% @dinosaurs.each do |dinosaur| %>
    <p><%= link_to dinosaur.name, dinosaur_path(dinosaur.id) %></p>
<% end %>

app/views/dinosaurs/new.erb
<h1>New Dinosaur</h1>

<%= form_for @dinosaur do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :age %>
    <%= f.number_field :age %>

    <%= f.label :image_url %>
    <%= f.text_field :image_url %>

    <%= f.submit "Create" %>
<% end %>

app/views/dinosaurs/show.html.erb
Rails.application.routes.draw do
   get 'dinosaurs' => 'dinosaur#index'
   get 'dinosaurs/new' => "dinosaurs#new"
   get 'dinosaurs/:id' => 'dinosaurs#show', as: :dinosaur
end

<h1><%= @dinosaur.name %></h1>

<p>Age: <%= @dinosaur.age %></p>
<%= image_tag @dinosaur.image_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ValleysOfDinosaurs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <br><br>
    <hr>

    <%= link_to "[All Dinosaurs]", root_path %>

  </body>
</html>